name: First Action
on:
  push:
    branches:
      - first
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Goodbye!"
